header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: CloudWeGo Authors

  paths:
    - '**/*.go'
    - '**/*.s'

  paths-ignore:
    - 'net_netfd.go'
    - 'net_sock.go'
    - 'net_sock_bsd.go'
    - 'net_sock_linux.go'
    - 'sys_exec_bsd.go'
    - 'sys_exec_linux.go'
    - 'net_tcpsock.go'
    - 'net_unixsock.go'
    - 'sys_sockopt_bsd.go'
    - 'sys_sockopt_linux.go'

  comment: on-failure